---
title: "ProblemSet_4"
author: "Behram Radmanesh"
format: 
  html:
      code-fold: true
      code-tools: true
      embed-resources: true
toc: true
---

[Github Link](https://github.com/MediciPrime/STATS506/tree/main/ProblemSet_4)

## Problem 1 - Tidyverse

### Part A
```{r}
library(nycflights13)
library(tidyverse)

# Mean & Median Departure Delay
flights %>%
  group_by(origin) %>%
  summarise(mean_dep_delay = mean(dep_delay, na.rm = TRUE),
            median_dep_delay = median(dep_delay, na.rm = TRUE),
            num_of_flights = n()) %>%
  ungroup() %>%
  filter(num_of_flights >= 10) %>%
  rename(faa = origin) %>%
  left_join(airports, by = "faa") %>%
  select(name, mean_dep_delay, median_dep_delay) %>%
  arrange(desc(mean_dep_delay))

# Mean & Median Arrival Delay
flights %>%
  group_by(dest) %>%
  summarise(mean_arr_delay = mean(arr_delay, na.rm = TRUE),
            median_arr_delay = median(arr_delay, na.rm = TRUE),
            num_of_flights = n()) %>%
  ungroup() %>%
  filter(num_of_flights >= 10) %>%
  rename(faa = dest) %>%
  left_join(airports, by = "faa") %>%
  select(name, mean_arr_delay, median_arr_delay) %>%
  arrange(desc(mean_arr_delay)) %>%
  print(n = 102)
```

### Part B

```{r}
flights %>%
  left_join(planes, by = "tailnum") %>%
  group_by(model) %>%
  summarize(avg_MPH = mean(distance/(air_time/60), na.rm = TRUE),
            num_of_flights = n()) %>%
  ungroup() %>%
  select(model, num_of_flights, avg_MPH) %>%
  arrange(desc(avg_MPH)) %>%
  slice(1)

```

## Problem 2 - get_temp()

```{r}


```


