---
title: "ProblemSet_3"
author: "Behram Radmanesh"
format: 
  html:
      code-fold: true
      code-tools: true
      embed-resources: true
toc: true
---

[Github Link](https://github.com/MediciPrime/STATS506/tree/main/ProblemSet_3)

## Problem 1 - Vision

### Part A

```{r}
library(kableExtra)
library(haven)

## Read in the XPT files
setwd("C:/Users/beh_2/Documents/STATS506/ProblemSet_3/data")
vision <- read_xpt("VIX_D.XPT")
demo <- read_xpt("DEMO_D.XPT")

## Merge 'vision' and 'demo' into 'main'
main <- merge(demo, vision, by = 'SEQN')

## Show the number of entries after merging
cat("Number of entries:", dim(main)[1])
```

### Part B

```{r}
## Create Column 'ageGroup' and subdivide 'RIDAGEYR' into it
main$ageGroup <- cut(main$RIDAGEYR, 
                     breaks = seq(0, max(main$RIDAGEYR) + 10, by=10),
                     labels = c("0-9", "10-19", "20-29", "30-39",
                                "40-49", "50-59", "60-69", "70-79",
                                "80-89"))

## Calculate Total Peope in ageGroup
ageGroupCounts <- table(main$ageGroup[main$VIQ220==1])
totalPeople <- sum(ageGroupCounts)

## Age Group Percentages
ageGroupPercentages <- (round(((ageGroupCounts/totalPeople)*100),
                        digits=1))

countsNPercentage <- table(main$ageGroup[main$VIQ220==1])
countsNPercentage <- rbind(countsNPercentage, ageGroupPercentages)
rownames(countsNPercentage) <- c("Counts", "Percentages")

## create a table with the valid proportions
countsNPercentage %>%
  kbl() %>%
  kable_paper("hover", full_width = F)
```

## Part C

Asked to predict whether a respondent wears glasses/contact lenses for distance vision.

```{r}
## Use RIDRETH1 for Race
## Use RIAGENDR for Gender
## Use INDFMPIR for PIR
## Use RIDAGEYR for Age
## Use VIQ220 for Glasses/Contact Lenses
mod1 <- lm(VIQ220==1 ~ RIDAGEYR, data = main)
summary(mod1)
AIC(mod1)

mod2 <- lm(VIQ220==1 ~ RIDAGEYR + RIDRETH1 + RIAGENDR, data = main)
summary(mod2)
AIC(mod2)

mod3 <- lm(VIQ220==1 ~ RIDAGEYR + RIDRETH1 + RIAGENDR + INDFMPIR,
           data = main)
summary(mod3)
AIC(mod3)

## Is 'pseudo-R^2 the same as adjusted-R^2?

```

## Part D

This part asks to determine if there is a difference between the number of men vs. women who wear distance corrective lenses.

```{r}
mod4 <- lm(VIQ220==1 ~ RIDAGEYR + RIDRETH1 + as.factor(RIAGENDR) 
           + INDFMPIR,
           data = main)

summary(mod4)

## Question: Would it be sufficient to utilize 'as.factor(RIAGENDR)'?
## Tried it and doesn't make a difference...
```



